/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VsButton: typeof import('./src/components/vscode/vs-button.vue')['default']
    VsCheckbox: typeof import('./src/components/vscode/vs-checkbox.vue')['default']
    VsDivider: typeof import('./src/components/vscode/vs-divider.vue')['default']
    VsDropdown: typeof import('./src/components/vscode/vs-dropdown.vue')['default']
    VsOption: typeof import('./src/components/vscode/vs-option.vue')['default']
    VsRadio: typeof import('./src/components/vscode/vs-radio.vue')['default']
    VsRadioGroup: typeof import('./src/components/vscode/vs-radio-group.vue')['default']
    VsTextArea: typeof import('./src/components/vscode/vs-text-area.vue')['default']
    VsTextField: typeof import('./src/components/vscode/vs-text-field.vue')['default']
  }
}
